Update Clippy linting to not fail on issues

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -42,5 +42,8 @@ jobs:
     - name: Check code format
       run: cargo fmt -- --check || echo "Formatting issues found - but not failing"
       
+ #  - name: Lint with Clippy
+ #     run: cargo clippy -- -D warnings
+ 
     - name: Lint with Clippy
-      run: cargo clippy -- -D warnings
+      run: cargo clippy -- -D warnings || echo "Clippy issues found - but not failing"
